spring:
  mvc:
    problemdetails:
      enabled: true

  data:
    mongodb:
        # Ensure you include /borrow_db in the URI
      uri: mongodb+srv://sahandhanujaya18:nR9xBKSBahjwjMGS@cluster-erp.e1dqwi1.mongodb.net/borrows?retryWrites=true&w=majority&appName=Cluster-erp
      database: borrows

  management:
    health:
      mongo:
        enabled: false  # This is the critical fix for Atlas

management:
  health:
    mongo:
      enabled: false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}