spring:
  application:
    name: borrow-service
  mvc:
    problemdetails:
      enabled: true

  data:
    mongodb:
      # Explicitly including the database name in the URI is the most reliable method
      uri: mongodb+srv://sahandhanujaya18:nR9xBKSBahjwjMGS@cluster-erp.e1dqwi1.mongodb.net/borrow_db?retryWrites=true&w=majority&appName=Cluster-erp
      database: borrow_db

management:
  health:
    mongo:
      enabled: false  # Keeps Actuator from failing on Atlas-restricted commands

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}