spring:
  cloud:
    config:
      enabled: true
  mongodb:
    uri: mongodb://sahandhanujaya18:nR9xBKSBahjwjMGS@ac-ga34wnr-shard-00-00.e1dqwi1.mongodb.net:27017,ac-ga34wnr-shard-00-01.e1dqwi1.mongodb.net:27017,ac-ga34wnr-shard-00-02.e1dqwi1.mongodb.net:27017/?replicaSet=atlas-p39acd-shard-0&ssl=true&authSource=admin
    database: borrow_db

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}